# Generated by Django 2.2.28 on 2026-09-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Kestrel Ridge College', max_length=255, verbose_name='school name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('office_hours', models.TextField(blank=True, verbose_name='office hours')),
                ('map_embed_url', models.URLField(blank=True, help_text='The src of an embeddable map iframe', max_length=500, verbose_name='map embed URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('footer_text', models.TextField(blank=True, verbose_name='footer text')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'school settings',
            },
        ),
    ]
