# Generated by Django 2.2.28 on 2026-09-22 04:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(classname='title')), ('size', wagtail.blocks.ChoiceBlock(choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]))])), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt_text', wagtail.blocks.CharBlock(help_text='Describe the image for screen readers', required=False)), ('caption', wagtail.blocks.CharBlock(required=False))])), ('quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('call_to_action', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock()), ('button_label', wagtail.blocks.CharBlock(default='Find out more'))])), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Paste a YouTube or Vimeo URL')), ('document', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('label', wagtail.blocks.CharBlock(help_text='Defaults to the document title', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='call to action label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='call to action page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=models.TextField(blank=True, verbose_name='hero intro'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='hero title'),
        ),
        migrations.CreateModel(
            name='HomePageQuickLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True, help_text='Used if no page is chosen')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
